# Site settings
title: Dart4Web.com
description: ""
url: https://stage.dart4web.com
baseurl: ""
permalink: /:title


# Build settings
safe: false
source: src
destination: _deploy
bundler_args: --without production
markdown: kramdown

include: ["_pages"]
exclude: ['vendor', '.asset-cache']

gems:
- jekyll-assets

assets:
  compress:
    css: true # default - development: false, production: true
    js: true # default - development: false, production: true
  cache: false # default: .asset-cache
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "*.eot"
    - "*.ttf"
    - "*.woff"
    - "*.svg"
  #   - "bundle.css"
  digest: true
  sources:
    - _assets/bower
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/media
  features:
    liquid: true # default: false
    automatic_img_size: true # default: true
    automatic_img_alt : true # default: true


