# Site settings
title: Dart4Web.com
description: ""
url: https://stage.dart4web.com
baseurl: ""
port: 4001
permalink: /:title

# Global variables
# use case:
#   {{site.dartlang}}/downloads
#
# for now... (comment these out)
# dart4web: "https://webdev.dartlang.org"
# dartlang: "https://www.dartlang.org"
# dart-vm:  "https://www.dartlang.org/dart-vm"
dartlang: "http://localhost:4000"
dart_vm:  "http://localhost:4000/dart-vm/"
#
flutter:  "https://flutter.io"
dartino:  "https://github.com/dartino"

collections:
  articles:
    output: true
    permalink: /articles/:path
  tutorials:
    output: true
    permalink: /tutorials/:path
  samples:
    output: true
    permalink: /samples/:path
  guides:
    output: true
    permalink: /guides/:path

defaults:
- scope:
    path: ""
    type: articles
  values:
    layout: article
    toc: true
- scope:
    path: ""
    type: tutorials
  values:
    layout: tutorial
    toc: true
- scope:
    path: ""
    type: samples
  values:
    layout: sample
    toc: true
- scope:
    path: ""
    type: guides
  values:
    layout: guide
    toc: true

# Build settings
safe: false
source: src
destination: publish
bundler_args: --without production
markdown: kramdown

include: ["_pages"]
exclude: ['vendor', '.asset-cache']

gems:
- jekyll-assets
- jekyll-toc

assets:
  compress:
    css: true # default - development: false, production: true
    js: true # default - development: false, production: true
  cache: false # default: .asset-cache
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "*.eot"
    - "*.ttf"
    - "*.woff"
    - "*.svg"
  #   - "bundle.css"
  digest: true
  sources:
    - _assets/icons
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/page_assets
  features:
    liquid: true # default: false
    automatic_img_size: true # default: true
    automatic_img_alt : true # default: true


