# Site settings
title: Dart4Web.com
description: ""
url: https://stage.dart4web.com
baseurl: ""
port: 4001
permalink: /:title

collections:
  articles:
    output: true
    permalink: /articles/:path
  tutorials:
    output: true
    permalink: /tutorials/:path
  codelabs:
    output: true
    permalink: /samples/:path

defaults:
- scope:
    path: articles
  values:
    layout: article
    toc: true
- scope:
    path: tutorials
  values:
    layout: tutorial
    toc: true
- scope:
    path: codelabs
  values:
    layout: codelab
    toc: true

# Build settings
safe: false
source: src
destination: _deploy
bundler_args: --without production
markdown: kramdown

include: ["_pages"]
exclude: ['vendor', '.asset-cache']

gems:
- jekyll-assets
- jekyll-toc

assets:
  compress:
    css: true # default - development: false, production: true
    js: true # default - development: false, production: true
  cache: false # default: .asset-cache
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "*.eot"
    - "*.ttf"
    - "*.woff"
    - "*.svg"
  #   - "bundle.css"
  digest: true
  sources:
    - _assets/bower
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/media
    - _assets/page_assets
  features:
    liquid: true # default: false
    automatic_img_size: true # default: true
    automatic_img_alt : true # default: true


